default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # 1. Increment build number
    # increment_build_number(xcodeproj: "Runner.xcodeproj")

    # 2. Build the app (Flutter way)
    # Unset Fastlane's Ruby environment so Flutter can run CocoaPods correctly
    sh "env -u GEM_HOME -u GEM_PATH -u RUBYOPT -u BUNDLE_BIN_PATH -u BUNDLE_GEMFILE flutter build ios --release --no-codesign"

    # 3. Upload to TestFlight
    # upload_to_testflight
  end
end
